### ISSUE TITLE
Add a mechanism for retaining a log of the quizzes we've completed

### ISSUE THREAD

**Issue by Gigabyte5671** [AlDrag/quizzaroo#11]
Or something similar.

**Comment by AlDrag** [comment]
Just like how we're leveraging corsproxy.io, maybe we need a free online database!

Maybe @ZeroX-DG has ideas.

**Comment by ZeroX-DG** [comment]
This one is difficult. Maybe we should solve the problem of embedding the quiz in an iframe first before thinking about this. Otherwise, retaining the log could be a bit awkward. Are we talking about the quizzes that we've done or does that include their score as well?

**Comment by AlDrag** [comment]
@ZeroX-DG persist as much as we want.

I don't think we can embed it in an iframe unfortunately. No way around it.

**Comment by ZeroX-DG** [comment]
Yeah the proxy that we're using right now doesn't allow spoofing the request origin. Setting up our own proxy is also an option.

**Comment by AlDrag** [comment]
The ethics is also coming into question. Not something I want to subject my github domain to 😅

**Comment by Gigabyte5671** [comment]
Haha yea. I'm thinking we should pass on the iframe idea.

As for the persistence mechanism, I have an idea... Will give it a quick test after work.

**Comment by Gigabyte5671** [comment]
Yeet

#14
