### ISSUE TITLE
When I enter a score, the hard word and three strikes sections grow

### ISSUE THREAD

**Issue by ryansname** [AlDrag/quizzaroo#15]
Expected behaviour:

The hard word and three strikes sections do not duplicate their contents when I enter a score.

![image](https://github.com/AlDrag/quizzaroo/assets/674165/93c0be57-b7c2-4aba-a196-850d6cfc13a4)

**Comment by Gigabyte5671** [comment]
I forgot to link this issue in the commit. This was fixed by [9001564](https://github.com/AlDrag/quizzaroo/commit/90015648d106dd7eb382b0092980b05fc617c403).
