### ISSUE TITLE
When entering a score, focus is lost after each input event

### ISSUE THREAD

**Issue by Gigabyte5671** [AlDrag/quizzaroo#16]
This is because the quiz list is re-rendered after each input event. [Reference](https://github.com/AlDrag/quizzaroo/blob/90015648d106dd7eb382b0092980b05fc617c403/script.js#L53)

Atm I can't think of a better way to do the two-way data binding for the inputs. @ZeroX-DG Do you have any ideas?

I don't really want to use `onchange` because of the edge case where an input is still focused when the tab is closed, which would cause that score not to be saved.

**Comment by ZeroX-DG** [comment]
Debounce FTW my friend 😄

**Comment by AlDrag** [comment]
Solved with [ffa92def30c](https://github.com/AlDrag/quizzaroo/commit/ffa92def30cf1617f980a2fc76c9084b664edebf).
