### ISSUE TITLE
Make the cursor looks like nyan cat!

### ISSUE THREAD

**Issue by ZeroX-DG** [AlDrag/quizzaroo#9]
The current rainbow cursor is nice, but imagine a nyan cat attached at the end.

**Comment by AlDrag** [comment]
Do it!

**Comment by ZeroX-DG** [comment]
![icegif-286](https://github.com/AlDrag/quizzaroo/assets/12984316/1fb79401-f9aa-4236-af57-bbaf11ac0a14)

**Comment by ZeroX-DG** [comment]
@Gigabyte5671 you're the CSS wizard!

**Comment by Gigabyte5671** [comment]
Holy moly!

Hmm, I'll have a think...
